### ISSUE TITLE
Empty log directories not removed

### ISSUE THREAD

**Issue by lukacu** [votchallenge/vot-toolkit#101]
Log directories are not removed after execution is done.

**Comment by yingjieyao** [comment]
If the tracker happens to down, we can't find the log files easily because it only reports that 'No result produced by tracker. Report written to....' while it's useless. We must to find the temporary folder It is very inconvenient. I wonder whether can put the log file together with the toolkit's log file.

**Comment by lukacu** [comment]
Hm, are you saying that the folded does not exist? Or is it just inconvenient to find it?

**Comment by yingjieyao** [comment]
The later.

**Comment by lukacu** [comment]
I am not sure if we can do anything about this since this would lead to huge log files. Having separate logs makes it easier to navigate them and delete instances where nothing interesting has happened. We are also working on parallel execution of experiments and in this case it is impossible to aggregate all the logs together in one file. I can think of how to make a specific log directory easier to find, this is probably the only possible solution.

**Comment by lukacu** [comment]
Logging has been updated for 5.0 so this is probably no longer relevant.
