### ISSUE TITLE
construct tracker.command

### ISSUE THREAD

**Issue by yingjieyao** [votchallenge/vot-toolkit#102]
When construct the tracker's command, maybe it's better to use`addpath(genpath('PATH_TO_TRACKER'))`  instead of  `addpath('PATH_TO_TRACKER')`, because most of coders are accustomed to put some third-party code in the sub-folder.

**Comment by lukacu** [comment]
Yes, adding sub-folders is a frequent pattern, however it is also not the only one. For example, you may want to exclude a certain sub-folder because in contains alternative implementation that override some functions ... in this case you may want to omit this entry. Because of this we will not implement this explicitly, however, I guess you can use genpath in your tracker description to generate the entire list of paths there. Please let me know if this works.

**Comment by yingjieyao** [comment]
Sorry to bother, I try my best but it doesn't works.  I try to find why but I failed. 
And I notice that only if I remove the definition of cleanup the error message can be wrote into the log file.

**Comment by lukacu** [comment]
Hm, are you referring to log writing or command construction?

**Comment by yingjieyao** [comment]
Sorry for my pool English and pool ability of description. 
My questions are:
- When I add genpath in the interface function, it doesn't work. This is for command construction.
- There is a definition of cleanup function like (cleanup = onCleanup(@() exit() );) at the start of the interface function. When the tracker has bugs or some other reasons that it can't work successfully, it will write the error message into the log file. But I notice that only if I remove the definition of the cleanup function the error message can be wrote into the log file. This is for log writing.

**Comment by lukacu** [comment]
Thank you for the reminder regarding log writing and cleanup function. We will change the recommended behavior of trackers to make this more clear.

**Comment by lukacu** [comment]
I think this was done, at least in the examples, closing issue.
