### ISSUE TITLE
Documentations of experiment

### ISSUE THREAD

**Issue by cybertk** [votchallenge/vot-toolkit#131]
I searched the whole projects in Github, including other projects under group **votchallenge**, only found one piece of documents of experiments 

* _Experiment_ - Evaluation of a tracker on a set of sequences in specific conditions. Specific experiment may change the original sequences to simulate some specific kind of circumstances (e.g. image noise, initialization error). 

So Is there a way/place to tell more details(w/o looking the code), including

- Spec/Purpose of each experiment
- Difference between existing 4 experiments(chunked, realtime, supervised, unsupervised)

**Comment by lukacu** [comment]
The current structure (separated experiments) is fairly recent so there was not time to document them yet. But I will put it on the todo.

**Comment by cybertk** [comment]
Thanks @lukca, could you explains a lit more if possible? I can help improve the documents after I understand them.

**Comment by lukacu** [comment]
Sure, there are at the moment four experiments:

- supervised: the default one, if the tracker goes below some overlap threshold it is reinitialized, you can set the threshold and initialization delay
- unsupervised: just run the tracker, it is a separate experiment to make it easier to identify and process separately
- realtime: considers per-frame runtime of the tracker, multiple options how to handle delays
- chunked: a test that we did some time ago, runs a tracker with periodic resets, may become a standard experiment in the future, but at the moment I am not even sure if it is completely functional because we were in a hurry with the changes required for the challenge.

**Comment by lukacu** [comment]
I think this was explained well enough in the previous comment, closing the issue. More information about relevant experiments are available in corresponding VOT papers.
