### ISSUE TITLE
[Suggestion] Please document the behavior of VOT API in python based trackers

### ISSUE THREAD

**Issue by gongbudaizhe** [votchallenge/vot-toolkit#138]
Hi, 

I am using python based trackers. In the sample python tracker, i,e, `python_ncc.py`, the standard method for integrating with the VOT API is:

```python
handle = vot.VOT("rectangle")
selection = handle.region()

imagefile = handle.frame()
if not imagefile:
    sys.exit(0)

image = cv2.imread(imagefile, cv2.IMREAD_GRAYSCALE)
tracker = NCCTracker(image, selection)
while True:
    imagefile = handle.frame()
    if not imagefile:
        break
    image = cv2.imread(imagefile, cv2.IMREAD_GRAYSCALE)
    region = tracker.track(image)
    handle.report(region)
``` 

It is worth noting that `handle.frame()` is used twice for the first frame. At first, I thought this is just for aesthetic reasons. But it turns out to be mandatory! Without it, the reported bboxes will always lag one step behind the current frame!

**Comment by lukacu** [comment]
Thank you for your comment. I am not sure where is the method called two times. The first call to handle.frame is for the first frame, the tracker should be initialized with the region at that time. The call within the loop is to obtain the second frame. The region for the first frame is automatically reported back because this was the old API way of doing this, this new API is just a cover for the TraX protocol. We will try to make this more clear when going through the documentation.

**Comment by gongbudaizhe** [comment]
Thanks for your detailed explanation.

I am not familiar with the TraX protocol, so my comments are based on the `vot.py` when `TRAX = False`.  In this file, we get frame by 

```python
  def frame(self):
    """
    Get a frame (image path) from client

    Returns:
        absolute path of the image
    """
    if TRAX:
      if hasattr(self, "_image"):
        image = str(self._image)
        del self._image
        return image

      request = self._trax.wait()

      if request.type == 'frame':
        return str(request.image)
      else:
        return None

    else:
      if self._frame >= len(self._files):
        return None
      return self._files[self._frame]
```

Since `TRAX = False`, in effect, we have

```python
new_frame = self._files[self._frame]
```
where `self._files` is a list with the image paths of the test video, `self._frame` is an integer for indexing and initialized to be 0.

I noticed that `self._frame` is only increased in the `report` function, 

```python
  def report(self, region):
    """
    Report the tracking results to the client

    Arguments:
        region: region for the frame
    """
    assert (isinstance(region, Rectangle) or isinstance(region, Polygon))
    if TRAX:
      if isinstance(region, Polygon):
        tregion = trax.region.Polygon([(x.x, x.y) for x in region.points])
      else:
        tregion = trax.region.Rectangle(region.x, region.y, region.width, region.height)
      self._trax.status(tregion)
    else:
      self._result.append(region)
      self._frame += 1
```

Since we did not report the bounding box in the initialization phase, we are actually still tracking the first frame in the while loop. This is the reason why I deem that handle.frame() is used twice for the first frame.

```python
while True:
    imagefile = handle.frame()
    if not imagefile:
        break
    image = cv2.imread(imagefile, cv2.IMREAD_GRAYSCALE)
    region = tracker.track(image)
    handle.report(region)
```

**Comment by Blenderama** [comment]
@gongbudaizhe Did you integrate python_ncc to the toolkit successfully? I have worked on this for a whole day but failed. I added the trax folder in sys.path in vot.py , so that TRAX=true. Otherwise it raises an error saying images.txt does not exist at this line:
`self._files = [x.strip('\n') for x in open('images.txt', 'r').readlines()]`

Can you tell me which value to set TRAX? How do you get the images.txt file?

**Comment by lukacu** [comment]
What do you mean by `TRAX = false` this option does not exist anymore since 2017 we have moved completely to TraX. But I see now that the Python wrapper still contained some old code, which will of course not work (the files that are required are not generated anymore). We will remove the old code, but I am not sure how did you bypass the protocol verification step.
