### ISSUE TITLE
repetitions in long term challenge

### ISSUE THREAD

**Issue by lawpdas** [votchallenge/vot-toolkit#234]
I cannot reproduce the same results by setting random seed. Can I change the repetitions for a stochastic long-term tracker?

**Comment by lukacu** [comment]
I am not really sure what do you mean? The long-term challenge should only run tracker once on every sequence.

**Comment by lawpdas** [comment]
I mean that each tracker should be evaluated more than once in case of randomness.

**Comment by lukacu** [comment]
Yes, this is supported and is done in short-term challenge, but there was a decision to skip it in long-term because sequences are longer, evaluation protocol is different and in general experiment take a long time (depending on tracker of course). You can increase the repetition count in the stack file, but this is not used in the challenge.
