### ISSUE TITLE
RGBT

### ISSUE THREAD

**Issue by Alexadlu** [votchallenge/vot-toolkit#237]
Hello, may I ask the organizing committee whether I can use the single-mode third-party algorithm, just change it into a multi-modal algorithm and use it to participate in the VOT-RGBT competition? I look forward to your reply. Thank you.

**Comment by alanlukezic** [comment]
Hi. Just re-running existing (third-party) algorithm is not allowed. On the other hand, modifying the existing algorithm is not against the rules (changing the algorithm to multi-modal seems ok). Also, make sure that you correctly reference the existing work and that you write which changes have been made in the short tracker description in the submission form. 
Note: such questions belong to the vot-challenge support forum rather than to the github.

**Comment by Alexadlu** [comment]
thanks your reply
