### ISSUE TITLE
502 Bad Gateway 

### ISSUE THREAD

**Issue by noUmbrella** [votchallenge/vot-toolkit#241]
When I submit my source code to VOT, I always receive the error of "502 Bad Gateway ". I have try 4 times.

**Comment by lukacu** [comment]
This is strange, the site works for me. Is your tracker really large? Because that could be an issue. So far we had code submissions under 100Mb.

**Comment by noUmbrella** [comment]
Yes, because I need upload the deep model, my submit file is 186MB.

**Comment by lukacu** [comment]
Well, we cannot debug it now, I am not even sure why the error even
occurred. Please submit the tracker without a model, and write a link where
the model is available. Also write me an email so that I will remember to
fix it later on. But this should not become a classical solution, I am only
saying this because it is the last day of the challenge.

**Comment by lukacu** [comment]
This will probably be fixed in the new submission form but is in any case not related to the toolkit.
