### ISSUE TITLE
Docker image for easier deployment on Linux

### ISSUE THREAD

**Issue by lukacu** [votchallenge/vot-toolkit#59]
Provide a Docker image that installs Octave and VOT toolkit.

**Comment by alantrrs** [comment]
This is a great idea, I'm currently working on this. I had this working a couple of months ago: https://github.com/alantrrs/vot-docker 
However, it's broken right now, I'm guessing because of [this reference] (https://github.com/votchallenge/vot-toolkit/blob/e348459367dab185e504e4d31ebfa7b7f7450a2c/workspace/workspace_load.m#L71) to trax.

I'm currently trying to upgrade it, so if you have any ideas on how you want to make this integration I can help.

**Comment by lukacu** [comment]
This would be great, if you have any ideas how this would be best taken care of please feel free to list them in the comments. I have at the moment only limited experience with Docker, but I guess that trax references should not be a problem, we can perhaps also pre-compile the binaries and distribute them as a layer.
