### ISSUE TITLE
How to integrate the tracker by using TraX protocol on Windows?

### ISSUE THREAD

**Issue by jzhang2008** [votchallenge/vot-toolkit#65]
When I integrate the ncc tracker in the VOT2014 evaluation kit by using TraX protocol on Windows, occur the error "Unable to start the tracker process". Who can tell me how to write the "tracker-comand=<TODO: set a tracker executable command>" in the tracker-ncc.m?

**Comment by lukacu** [comment]
Tracker integration is explained [here](http://votchallenge.net/howto/integration.html), there is a special section for Matlab trackers that are a bit special because of the limitations of the environment. Please post further questions to the [support forum](https://groups.google.com/forum/?hl=en#!forum/votchallenge-help), the issue tracker is for software bugs and feature requests.
