### ISSUE TITLE
Re-initialization of trackers

### ISSUE THREAD

**Issue by egundogdu** [votchallenge/vot-toolkit#67]
Hi, 
I have been using VOT 2014 and observed that if a tracker fails it does not re-start immediately. I have also read the new performance metroc of VOT 2015 which uses the accuracy outputs of the VOT 2014. 
So my question is: why the framework does not detect the failure (zero overlap) and re-start the tracker from the frame where it should start ? Since it doesn't do so, the framework waits till the end of the sequence although the tracker failed at the very beginning of the sequence. It is really time consuming if your tracker fails mostly in long sequences.

Thanks.
Erhan

**Comment by lukacu** [comment]
Hello, this is probably due to using a legacy file-based protocol for communication with a tracker, you should switch to TraX. The old protocol works like people usually expect it: the toolkit generates some files, runs a tracker that also produces some files and then the toolkit checks where the trackers has failed. This is of course not optimal, but we have left it in the toolkit because we felt that people are not ready to invest a bit more effort into integration at the time. We will be slowly abandoning the support for it so I suggest that you check our [support pages](http://votchallenge.net/howto/) on how to enable TraX support in your tracker.

**Comment by lukacu** [comment]
I have opened a new issue for the warning message: #68
