### ISSUE TITLE
Lack of instructions for Linux & Octave

### ISSUE THREAD

**Issue by L-Ron-GitHubbard** [votchallenge/vot-toolkit#70]
Hi,

I'm trying to follow the instructions on http://www.votchallenge.net/howto/workspace.html and http://www.votchallenge.net/howto/integration.html. Unfortunately, there is no tutorial yet on how to get it working with Octave. I'm guessing that functions like generate_matlab_command() perhaps need an Octave equivalent also?

Could you please test that the current toolkit works with the latest Octave and provide a tutorial on getting it to work?

Thanks in advance!

p.s. I've gotten as far as setting up the workspace, but can't get run_test() to work even on the provided ncc.m tracker. The following error always pops up:

error: 'nargin' undefined near line 36 column 7
error: called from
    **unimplemented** at line 36 column 3
    create_sequence at line 51 column 17
    load_sequences at line 67 column 21
    workspace_load at line 117 column 15
    run_test.m at line 6 column 24

I'm using Octave 4.0.0 by the way.

**Comment by lukacu** [comment]
Are you referring to using Octave to run the toolkit or is your tracker interpreted by Octave? The first case should be supported (at least the execution of experiments, the analysis is not well supported due to poor plotting functionality in Octave), the second option is not, therefore having a generate_octave_command is not really needed (of course we are accepting community contributions, technically it is definitely possible, probably even easier than supporting Matlab). We do not have resources to check every Octave incompatibility that occurs with a new version. It was definitely working in previous versions. The error is also very strange, just to make things clear, you are referring to the most recent trunk version of the toolkit? Because the lines that the error is referring to are very rudimentary, I am not sure why they would cause an error.

**Comment by L-Ron-GitHubbard** [comment]
Thanks for the quick reply.

I am trying to use Octave to both run the toolkit and interpret the 
tracker.
My own tracker is developed in Octave and I do not currently have Matlab 
available.

When I recently learned about the VOT toolkit and that it was designed 
to also support Octave, I assumed I would be able to use Octave to run 
the VOT toolkit and evaluate my Octave-interpreted tracker with it. 
Using multiple active Octave instances is not a problem as far as I know.
If I understand you correctly, Octave-interpreted trackers are not yet 
supported by the toolkit however?

Perhaps then I'll see if I can make a minimum of changes to the toolkit 
code to make it work for Octave-interpreted trackers also.

As for now, I have not looked into the error yet, but that line of code 
indeed looks very basic. Probably just the manifestation of another 
problem earlier in the code.

**Comment by lukacu** [comment]
Well, nobody has so far attempted to run an Octave tracker so the issue has not been raised. Because of the limited resources we are trying to ensure support for most common platforms and leave the rest to the community, we would be happy to accept fixes, but they should be conceptually sound and not break any existing functionality. For Octave I imagine that a generate_octave_command() should be created that locates the Octave executable and adds appropriate command-line flags. Then also TraX support should be tested ... we have not done this so far because there was no interest from the community.

**Comment by lukacu** [comment]
Recent updates have resolved some Octave issues when it comes to evaluation, however, we still do not support octave-based trackers, this is something that can be added if there is some interest in the community.

**Comment by lukacu** [comment]
Support for Octave has been added and is similarly stable to Octave itself, but it is there. I am therefore closing the issue.
